import path from "node:path";
import { fileURLToPath } from "node:url";

import tsEslint from "@typescript-eslint/eslint-plugin";
import tsParser from "@typescript-eslint/parser";
import importPlugin from "eslint-plugin-import";
import globals from "globals";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

export default [
  {
    ignores: [
      "dist/",
      "node_modules/",
      // wasm-bindgen-generated glue + .d.ts shipped from the
      // Rust ballistic-solver pilot crate. Regenerated by
      // scripts/build-wasm-ballistic-solver.ps1; not project source.
      "src/systems/combat/projectiles/wasm/**",
    ],
  },
  {
    files: ["**/*.{ts,tsx}"],
    languageOptions: {
      parser: tsParser,
      parserOptions: {
        project: ["./tsconfig.eslint.json"],
        tsconfigRootDir: __dirname,
        sourceType: "module",
      },
    },
    plugins: {
      "@typescript-eslint": tsEslint,
      import: importPlugin,
    },
    settings: {
      "import/resolver": {
        typescript: {
          project: ["./tsconfig.eslint.json"],
        },
      },
    },
    rules: {
      ...tsEslint.configs.recommended.rules,
      "no-console": "warn",
      "@typescript-eslint/ban-ts-comment": "off",
      "@typescript-eslint/no-explicit-any": "off",
      "@typescript-eslint/no-non-null-assertion": "off",
      "@typescript-eslint/no-unused-vars": ["error", {
        "argsIgnorePattern": "^_",
        "varsIgnorePattern": "^_",
        "caughtErrorsIgnorePattern": "^_"
      }],
      "import/no-cycle": ["warn", { maxDepth: 3, ignoreExternal: true }],
    },
  },
  {
    files: [
      "**/*.worker.{ts,tsx}",
      "**/*worker*.{ts,tsx}",
      "src/workers/**/*.{ts,tsx}",
    ],
    rules: {
      "no-console": "off",
    },
  },
  {
    // Repo automation/probe scripts run under Node (tsx), not in the browser.
    // They legitimately use console + process and live in their own TS project
    // (tsconfig.scripts.json) so the type-aware parser can resolve them.
    files: ["scripts/**/*.ts"],
    languageOptions: {
      parser: tsParser,
      parserOptions: {
        project: ["./tsconfig.scripts.json"],
        tsconfigRootDir: __dirname,
        sourceType: "module",
      },
      globals: {
        ...globals.node,
      },
    },
    rules: {
      "no-console": "off",
    },
  },
  {
    files: ["**/*.test.ts", "**/*.spec.ts"],
    rules: {
      "@typescript-eslint/no-require-imports": "off",
      "@typescript-eslint/no-unsafe-function-type": "off",
      "@typescript-eslint/no-unused-vars": "warn",
      "no-console": "off",
    },
  },
];
