// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (c) 2025-2026 Matthew Kissinger

/**
 * Central registry of GLB model paths relative to public/models/.
 * Used by ModelLoader.loadModel() throughout the engine.
 *
 * Single-writer rule (cycle-2026-06-11-war-asset-repaint): these constants are
 * GENERATED by `npm run assets:import-war-catalog` into
 * `src/config/generated/warAssetCatalog.ts`. This module is a stable re-export
 * so existing imports (`WeaponModels`, `AircraftModels`, …) keep their paths
 * while the catalog grows from the import manifest. Do not hand-edit the path
 * tables — re-run the importer. The generated catalog also exposes per-slug
 * import metadata (measured dims, tris, on-disk forward axis, budget triage
 * status, grafted rig joints, magazine/muzzle anchors) via `warAssetCatalog`.
 */

export {
  WeaponModels,
  AircraftModels,
  GroundVehicleModels,
  WatercraftModels,
  StructureModels,
  BuildingModels,
  AnimalModels,
  PropModels,
  warAssetCatalog,
} from '../../config/generated/warAssetCatalog';

export type {
  WarAssetEntry,
  WarAssetJoint,
  WarAssetForward,
  WarAssetBudgetStatus,
} from '../../config/generated/warAssetCatalog';
